{
 "title": "WSO2 Proxy Service Metrics",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(wso2_integration_service_up{service_type=\"proxy\"}, namespace)"
   },
   {
    "name": "service",
    "label": "Service Name",
    "query": "label_values(wso2_integration_service_up{service_type=\"proxy\", namespace=\"$namespace\"}, service_name)"
   },
   {
    "name": "node",
    "label": "Node Name",
    "query": "label_values(wso2_integration_service_up{service_name=\"$service\"}, instance)"
   },
   { "name": "jaegerHost", "query": "localhost:8080" }
  ]
 },
 "panels": [
  { "title": "[[service]]", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "service" },
  {
   "title": "Up Time",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "time() - max(wso2_integration_service_up{service_name=\"[[service]]\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "All Request Count",
   "type": "stat",
   "description": "Displays all time request count served by this proxy service. This will also include the error requests.",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(wso2_integration_proxy_request_count_total{service_name=\"[[service]]\", namespace=\"$namespace\"}[$__range])-min_over_time(wso2_integration_proxy_request_count_total{service_name=\"[[service]]\", namespace=\"$namespace\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Successful Request Count",
   "type": "stat",
   "description": "Displays approximate request count received by this proxy service within the selected time range.",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(max_over_time(wso2_integration_proxy_request_count_total{service_name=\"[[service]]\", namespace=\"$namespace\"}[$__range])-min_over_time(wso2_integration_proxy_request_count_total{service_name=\"[[service]]\", namespace=\"$namespace\"}[$__range])))-(sum(max_over_time(wso2_integration_proxy_request_count_error_total{service_name=\"[[service]]\", namespace=\"$namespace\"}[$__range])-min_over_time(wso2_integration_proxy_request_count_error_total{service_name=\"[[service]]\", namespace=\"$namespace\"}[$__range])))"
    }
   ]
  },
  {
   "title": "Error Count",
   "type": "stat",
   "description": "Displays all time error count occurred within this proxy service. Use below link to visit error logs for this service for this time period",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(wso2_integration_proxy_request_count_error_total{service_name=\"[[service]]\", namespace=\"$namespace\"}[$__range])-min_over_time(wso2_integration_proxy_request_count_error_total{service_name=\"[[service]]\", namespace=\"$namespace\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Error Percentage",
   "type": "stat",
   "description": "Displays number of error requests occurred during the selected time range.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(wso2_integration_proxy_request_count_error_total{service_name=\"[[service]]\", namespace=\"$namespace\"}[$__range])-min_over_time(wso2_integration_proxy_request_count_error_total{service_name=\"[[service]]\", namespace=\"$namespace\"}[$__range]))/sum(max_over_time(wso2_integration_proxy_request_count_total{service_name=\"[[service]]\", namespace=\"$namespace\"}[$__range])-min_over_time(wso2_integration_proxy_request_count_total{service_name=\"[[service]]\", namespace=\"$namespace\"}[$__range]))",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Deployed Node Count",
   "type": "stat",
   "description": "Displays number of nodes this proxy service is deployed.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(wso2_integration_service_up{service_name=\"[[service]]\", namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Request Rate",
   "type": "graph",
   "description": "Displays the request rate for this proxy service.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "reqps", "label": "TPS" }
   ],
   "targets": [
    {
     "expr": "sum(rate(wso2_integration_proxy_request_count_total{service_name=\"[[service]]\", namespace=\"$namespace\", }[$__interval]))"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "graph",
   "description": "Displays error rate of this proxy service.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "TPS" }
   ],
   "targets": [
    {
     "expr": "sum(rate(wso2_integration_proxy_request_count_error_total{service_name=\"[[service]]\", namespace=\"$namespace\"}[$__interval]))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "heatmap",
   "description": "Displays the response time of all requests served by this proxy service in a heat map. Each tile will represent number of requests which fell in to the pre-defined time bucket during the bucket time span. If you seen any anomalies  please use the below link to view tracing information related to [[service]]",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 6 },
   "targets": [
    {
     "expr": "sum by (le)(increase(wso2_integration_proxy_latency_seconds{service_name=\"[[service]]\", namespace=\"$namespace\", le=~\".+\"}[5m]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "{service=\"{proxy:[[service]]}\"}"
    }
   ]
  }
 ]
}